# Data Glossary
| Column | Description |
|---------|-------------|
| **keyword** | Search keyword used to retrieve the job posting. |
| **job_id** | Unique identifier of the job posting. |
| **title** | Job title. |
| **company** | Employer or company name. |
| **province** | Province where the job is located. |
| **city** | City where the job is located. |
| **salary_visible** | Indicates whether salary information is publicly visible. |
| **experience_years** | Minimum required years of work experience. |
| **description** | Cleaned job description. |
| **work_type** | Employment type (Full Time, Part Time, Internship, etc.). |
| **seniority** | Required seniority level. |
| **category** | Job category assigned by JobVision. |
| **company_size** | Company size based on number of employees. |
| **industries** | Company's industry sectors. |
| **benefits** | Benefits and perks offered by the employer. |
| **salary_title** | Salary range displayed as text. |
| **salary_min** | Minimum salary (Million Tomans). |
| **salary_max** | Maximum salary (Million Tomans). |
| **gender** | Preferred applicant gender, if specified. |
| **required_age_min** | Minimum required age. |
| **required_age_max** | Maximum required age. |
| **military** | Indicates whether military service completion is required. |
| **work_days** | Working schedule. |
| **business_trip** | Required business travel. |
| **software** | Required software, programming languages, and technologies. |
| **software_levels** | Required proficiency level for each listed software skill. |
| **first_activation** | Date when the job was first published. |
| **activation** | Latest activation (refresh) date. |
| **expire** | Job expiration date. |
| **application_count** | Number of submitted applications. |
| **internship** | Indicates whether the position is an internship. |
| **remote** | Indicates whether remote work is available. |
| **urgent** | Indicates whether the vacancy is marked as urgent. |

In [7]:
import pandas as pd
from pathlib import Path
import sys
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
df = pd.read_csv("../data/processed/jobs_clean.csv")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

In [9]:
print(df.shape[0], 'x', df.shape[1])
df.head()

12255 x 33

,keyword,job_id,title,company,province,city,salary_visible,experience_years,description,work_type,seniority,category,company_size,industries,benefits,salary_title,salary_min,salary_max,gender,required_age_min,required_age_max,military,work_days,business_trip,software,software_levels,first_activation,activation,expire,application_count,internship,remote,urgent
0,python,1396130,برنامه نویس Python,بارکس,تهران,تهران,False,5,ما برای توسعه ERP شرکت بر پایه Odoo به دنبال یک توسعه‌دهنده مسلط هستیم که تو...,Full Time,Senior Specialist,"IT - Software Development (Web,Moblie,…)",11 - 50 employees,Transportation / Logistics,"Loan,Bonus,Snacks\r\n,Occasional packages and gifts",NaN,NaN,NaN,Men / Women,NaN,NaN,False,شنبه تا چهارشنبه 8ت5پنج شنبه از 8صبح الی2,NaN,"Python,Oracle Database,GIT","Advanced,Basic,Basic",2026-05-20 15:30:13,2026-05-20 15:30:13,2026-07-19 15:30:13,495.0,False,False,True
1,python,1401623,Senior Backend Engineer(Python/FastAPI)- Shoraka,بیمه بازار,تهران,تهران,False,3,We are looking for a Senior Backend Engineer to join our team and contribute...,Full Time,Senior Specialist,"IT - Software Development (Web,Moblie,…)",501 - 1000 employees,"Internet Provider / E-commerce / Online Services,Insurance",NaN,NaN,NaN,NaN,Men / Women,NaN,NaN,False,Saturday to Wednesday,NaN,"Python,PostgreSql,Prometheus,Gerafana,Docker,Redis,Kubernetes","Advanced,Intermediate,Intermediate,Intermediate,Intermediate,Intermediate,In...",NaN,NaN,NaN,805.0,False,True,True
2,python,1436012,برنامه نویس Python,ارتباطات فرهنگ آزما,تهران,تهران,False,2,ما در تیم تحقیق و توسعه فرهنگ آزما به دنبال یک توسعه دهنده Backend هستیم تا ...,Full Time,Specialist,"IT - Software Development (Web,Moblie,…)",11 - 50 employees,"IT / Software / Hardware,Internet Provider / E-commerce / Online Services",Occasional packages and gifts,NaN,NaN,NaN,Men / Women,22.0,40.0,False,شنبه تا چهارشنبه 8:30 الی 18,NaN,"Python,Django,GIT,MySql,PostgreSql,Redis,Linux,Rest API,Unit Testing","Advanced,Advanced,Advanced,Intermediate,Intermediate,Basic,Intermediate,Inte...",NaN,NaN,NaN,354.0,False,False,False
3,python,1390562,برنامه نویس بک‌اند (Python/Django),شرکت بیمۀ زندگی باران,تهران,تهران,False,3,اگر توسعه‌دهنده‌ای هستید که چالش‌های فنی شما را هیجان‌زده می‌کند و به ساخت ر...,Full Time,Specialist,"IT - Software Development (Web,Moblie,…)",11 - 50 employees,Insurance,"Loan,Bonus,Health insurance\r\n,Flexible working hours\r\n,Learning stipends...",NaN,NaN,NaN,Men / Women,23.0,33.0,True,شنبه تا سه شنبه از 08:00 الی 17:00 و چهارشنبه از ساعت 08:00 الی ساعت 16:00 (...,NaN,"Python,Django,GIT,Linux","Intermediate,Intermediate,Basic,Basic",2026-05-25 09:28:51,2026-06-14 09:28:52,2026-07-24 09:28:51,882.0,False,False,True
4,python,1429358,برنامه نویس Python,شرکت پیشگامان توسعه ارتباطات,تهران,تهران,False,2,نکات فنی: تسلط بر Django آشنایی با DRF آشنایی با Design Patterns آشنایی با G...,Full Time,Specialist,"IT - Software Development (Web,Moblie,…)",201 - 500 employees,"IT / Software / Hardware,Internet Provider / E-commerce / Online Services","Health insurance\r\n,Occasional packages and gifts",NaN,NaN,NaN,Men / Women,19.0,40.0,True,شنبه تا سه‌شنبه 8 تا 17، چهارشنبه 8 تا 16,NaN,"Linux,Django,GIT,Python","Intermediate,Advanced,Intermediate,Intermediate",NaN,NaN,NaN,587.0,False,False,False

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12255 entries, 0 to 12254
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   keyword            12255 non-null  str
 1   job_id             12255 non-null  int64
 2   title              12255 non-null  str
 3   company            12255 non-null  str
 4   province           12231 non-null  str
 5   city               12255 non-null  str
 6   salary_visible     12255 non-null  bool
 7   experience_years   12255 non-null  int64
 8   description        12255 non-null  str
 9   work_type          12255 non-null  str
 10  seniority          12255 non-null  str
 11  category           12255 non-null  str
 12  company_size       12255 non-null  str
 13  industries         12255 non-null  str
 14  benefits           9899 non-null   str
 15  salary_title       4165 non-null   str
 16  salary_min         4165 non-null   float64
 17  salary_max         4165 non-null   float64
 18  gender             12255 non-null  str
 19  required_age_min   8143 non-null   float64
 20  required_age_max   8247 non-null   float64
 21  military           12255 non-null  bool
 22  work_days          12255 non-null  str
 23  business_trip      1025 non-null   str
 24  software           8660 non-null   str
 25  software_levels    8660 non-null   str
 26  first_activation   8741 non-null   str
 27  activation         8741 non-null   str
 28  expire             8741 non-null   str
 29  application_count  11828 non-null  float64
 30  internship         12255 non-null  bool
 31  remote             12255 non-null  bool
 32  urgent             12255 non-null  bool
dtypes: bool(5), float64(5), int64(2), str(21)
memory usage: 2.7 MB

In [10]:
dtype_df = (df.dtypes.astype(str).reset_index())
dtype_df.columns = ["Column", "Data Type"]
dtype_df

               Column Data Type
0             keyword       str
1              job_id     int64
2               title       str
3             company       str
4            province       str
5                city       str
6      salary_visible      bool
7    experience_years     int64
8         description       str
9           work_type       str
10          seniority       str
11           category       str
12       company_size       str
13         industries       str
14           benefits       str
15       salary_title       str
16         salary_min   float64
17         salary_max   float64
18             gender       str
19   required_age_min   float64
20   required_age_max   float64
21           military      bool
22          work_days       str
23      business_trip       str
24           software       str
25    software_levels       str
26   first_activation       str
27         activation       str
28             expire       str
29  application_count   float64
30         internship      bool
31             remote      bool
32             urgent      bool

In [11]:
missing = (df.isna().sum().to_frame("Missing"))
missing["Percent"] = (missing["Missing"] / len(df) * 100).round(2)
missing = (missing.sort_values("Percent", ascending=False))
missing

                   Missing  Percent
business_trip        11230    91.64
salary_max            8090    66.01
salary_min            8090    66.01
salary_title          8090    66.01
required_age_min      4112    33.55
required_age_max      4008    32.71
software_levels       3595    29.33
software              3595    29.33
activation            3514    28.67
expire                3514    28.67
first_activation      3514    28.67
benefits              2356    19.22
application_count      427     3.48
province                24     0.20
keyword                  0     0.00
city                     0     0.00
job_id                   0     0.00
industries               0     0.00
seniority                0     0.00
category                 0     0.00
company_size             0     0.00
work_type                0     0.00
salary_visible           0     0.00
experience_years         0     0.00
description              0     0.00
company                  0     0.00
title                    0     0.00
gender                   0     0.00
work_days                0     0.00
military                 0     0.00
internship               0     0.00
remote                   0     0.00
urgent                   0     0.00

In [13]:
duplicate_rows = df.duplicated().sum()
print(f"Duplicate Rows : {duplicate_rows}")
duplicate_jobs = df["job_id"].duplicated().sum()
print(f"Duplicate Job IDs : {duplicate_jobs}")

Duplicate Rows : 0
Duplicate Job IDs : 0

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
job_id,12255.0,1.418581e+06,45014.597606,233685.0,1408959.0,1424435.0,1438384.50,1452138.0
experience_years,12255.0,2.903876e+00,2.020799,0.0,2.0,3.0,4.00,20.0
salary_min,4165.0,3.790996e+01,22.475567,3.0,25.0,30.0,45.00,400.0
salary_max,4165.0,5.239784e+01,30.663217,4.0,35.0,45.0,60.00,500.0
required_age_min,8143.0,2.487670e+01,4.296266,18.0,22.0,25.0,27.00,50.0
required_age_max,8247.0,3.848842e+01,5.374126,20.0,35.0,40.0,40.00,50.0
application_count,11828.0,2.785853e+02,317.998423,11.0,67.0,154.0,379.25,4660.0