In [1]:
from pathlib import Path
import pandas as pd
import ast
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

DATA_PATH = Path("../data/processed/jobs_cleaned_df.csv")
df = pd.read_csv(DATA_PATH)

In [2]:
df.head()

,keyword,job_id,title,company,province,city,salary_visible,experience_years,description,work_type,seniority,category,company_size,industries,benefits,salary_title,salary_min,salary_max,gender,required_age_min,required_age_max,military,work_days,business_trip,software,software_levels,first_activation,activation,expire,application_count,internship,remote,urgent,skills_structured,skills_normalized,benefits_clean,industries_clean
0,python,1396130,برنامه نویس Python,بارکس,تهران,تهران,False,5,ما برای توسعه ERP شرکت بر پایه Odoo به دنبال یک توسعه دهنده مسلط هستیم که توانایی توسعه ماژول ها...,Full Time,Senior Specialist,"IT - Software Development (Web,Moblie,…)",11 - 50 employees,Transportation / Logistics,"Loan,Bonus,Snacks\r\n,Occasional packages and gifts",NaN,NaN,NaN,Men / Women,NaN,NaN,False,شنبه تا چهارشنبه 8ت5پنج شنبه از 8صبح الی2,NaN,"Python,Oracle Database,GIT","Advanced,Basic,Basic",2026-05-20 15:30:13,2026-05-20 15:30:13,2026-07-19 15:30:13,495.0,False,False,True,"[{'skill': 'Python', 'level': 'Advanced'}, {'skill': 'Oracle Database', 'level': 'Basic'}, {'ski...","[{'skill': 'Python', 'level': 'Advanced'}, {'skill': 'Oracle Database', 'level': 'Basic'}, {'ski...","['Loan', 'Bonus', 'Snacks', 'Occasional packages and gifts']",['Transportation / Logistics']
1,python,1401623,Senior Backend Engineer(Python/FastAPI)- Shoraka,بیمه بازار,تهران,تهران,False,3,We are looking for a Senior Backend Engineer to join our team and contribute to the development ...,Full Time,Senior Specialist,"IT - Software Development (Web,Moblie,…)",501 - 1000 employees,"Internet Provider / E-commerce / Online Services,Insurance",NaN,NaN,NaN,NaN,Men / Women,NaN,NaN,False,Saturday to Wednesday,NaN,"Python,PostgreSql,Prometheus,Gerafana,Docker,Redis,Kubernetes","Advanced,Intermediate,Intermediate,Intermediate,Intermediate,Intermediate,Intermediate",NaN,NaN,NaN,805.0,False,True,True,"[{'skill': 'Python', 'level': 'Advanced'}, {'skill': 'PostgreSql', 'level': 'Intermediate'}, {'s...","[{'skill': 'Python', 'level': 'Advanced'}, {'skill': 'PostgreSQL', 'level': 'Intermediate'}, {'s...",[],"['Internet Provider / E-commerce / Online Services', 'Insurance']"
2,python,1436012,برنامه نویس Python,ارتباطات فرهنگ آزما,تهران,تهران,False,2,ما در تیم تحقیق و توسعه فرهنگ آزما به دنبال یک توسعه دهنده Backend هستیم تا به تیم ما بپیوندد و ...,Full Time,Specialist,"IT - Software Development (Web,Moblie,…)",11 - 50 employees,"IT / Software / Hardware,Internet Provider / E-commerce / Online Services",Occasional packages and gifts,NaN,NaN,NaN,Men / Women,22.0,40.0,False,شنبه تا چهارشنبه 8:30 الی 18,NaN,"Python,Django,GIT,MySql,PostgreSql,Redis,Linux,Rest API,Unit Testing","Advanced,Advanced,Advanced,Intermediate,Intermediate,Basic,Intermediate,Intermediate,Basic",NaN,NaN,NaN,354.0,False,False,False,"[{'skill': 'Python', 'level': 'Advanced'}, {'skill': 'Django', 'level': 'Advanced'}, {'skill': '...","[{'skill': 'Python', 'level': 'Advanced'}, {'skill': 'Django', 'level': 'Advanced'}, {'skill': '...",['Occasional packages and gifts'],"['IT / Software / Hardware', 'Internet Provider / E-commerce / Online Services']"
3,python,1390562,برنامه نویس بک‌اند (Python/Django),شرکت بیمۀ زندگی باران,تهران,تهران,False,3,اگر توسعه دهنده ای هستید که چالش های فنی شما را هیجان زده می کند و به ساخت راهکارهای خلاقانه علا...,Full Time,Specialist,"IT - Software Development (Web,Moblie,…)",11 - 50 employees,Insurance,"Loan,Bonus,Health insurance\r\n,Flexible working hours\r\n,Learning stipends\r\n,Purchasing coup...",NaN,NaN,NaN,Men / Women,23.0,33.0,True,شنبه تا سه شنبه از 08:00 الی 17:00 و چهارشنبه از ساعت 08:00 الی ساعت 16:00 (با یک ساعت شناوری صبح),NaN,"Python,Django,GIT,Linux","Intermediate,Intermediate,Basic,Basic",NaN,NaN,NaN,882.0,False,False,True,"[{'skill': 'Python', 'level': 'Intermediate'}, {'skill': 'Django', 'level': 'Intermediate'}, {'s...","[{'skill': 'Python', 'level': 'Intermediate'}, {'skill': 'Django', 'level': 'Intermediate'}, {'s...","['Loan', 'Bonus', 'Health insurance', 'Flexible working hours', 'Learning stipends', 'Purchasing...",['Insurance']
4,python,1429358,برنامه نویس Python,شرکت پیشگامان توسعه ارتباطات,تهران,تهران,False,2,نکات فنی: تسلط بر Django آشنایی با DRF آشنایی با Design Patterns آشنایی با Git داشتن آشنایی و سا...,Full Time,Specialist,"IT - Software Development (Web,Moblie,…)",201 - 500 employees,"IT / Software / Hardware,Internet Provider / E-commerce / Online Services","Health insurance\r\n,Occasional packages and gifts",NaN,NaN,NaN,Men / Women,19.0,40.0,True,شنبه تا سه‌شنبه 8 تا 17، چهارشنبه 8 تا 16,NaN,"Linux,Django,GIT,Python","Intermediate,Advanced,Intermediate,Intermediate",2026-06-22 15:16:03,2026-06-22 15:16:03,2026-08-21 15:16:03,587.0,False,False,False,"[{'skill': 'Linux', 'level': 'Intermediate'}, {'skill': 'Django', 'level': 'Advanced'}, {'skill'...","[{'skill': 'Linux', 'level': 'Intermediate'}, {'skill': 'Django', 'level': 'Advanced'}, {'skill'...","['Health insurance', 'Occasional packages and gifts']","['IT / Software / Hardware', 'Internet Provider / E-commerce / Online Services']"

In [3]:
df["skill_count"] = df["skills_normalized"].apply(len)

In [4]:
df["skill_count"].describe()

count    12037.000000
mean       113.216582
std        106.427737
min          2.000000
25%          2.000000
50%        101.000000
75%        169.000000
max        965.000000
Name: skill_count, dtype: float64

In [5]:
df["skills_normalized"].apply(type).value_counts()

skills_normalized
<class 'str'>    12037
Name: count, dtype: int64

In [6]:
def parse_list_string(value):
    """
    Convert string representation of Python objects back to real objects.
    """
    if pd.isna(value):
        return []

    if isinstance(value, list):
        return value

    return ast.literal_eval(value)

df["skills_normalized"] = df["skills_normalized"].apply(parse_list_string)

In [7]:
df["skills_normalized"].apply(type).value_counts()

skills_normalized
<class 'list'>    12037
Name: count, dtype: int64

In [8]:
df["skill_count"] = df["skills_normalized"].apply(len)

In [9]:
df["skill_count"].describe()

count    12037.000000
mean         2.304146
std          2.234126
min          0.000000
25%          0.000000
50%          2.000000
75%          3.000000
max         20.000000
Name: skill_count, dtype: float64

In [10]:
df["skills_normalized"].explode()[:10]

0            {'skill': 'Python', 'level': 'Advanced'}
0      {'skill': 'Oracle Database', 'level': 'Basic'}
0                  {'skill': 'Git', 'level': 'Basic'}
1            {'skill': 'Python', 'level': 'Advanced'}
1    {'skill': 'PostgreSQL', 'level': 'Intermediate'}
1    {'skill': 'Prometheus', 'level': 'Intermediate'}
1      {'skill': 'Gerafana', 'level': 'Intermediate'}
1        {'skill': 'Docker', 'level': 'Intermediate'}
1         {'skill': 'Redis', 'level': 'Intermediate'}
1    {'skill': 'Kubernetes', 'level': 'Intermediate'}
Name: skills_normalized, dtype: object

## Skill Level Score
Skill levels are converted into numerical values:
- Basic = 1
- Intermediate = 2
- Advanced = 3
The total score represents the overall technical skill requirement of a job.

In [11]:
skill_level_mapping = {
    "Basic": 1,
    "Intermediate": 2,
    "Advanced": 3
}

def calculate_skill_level_score(skills):
    """
    Calculate total skill level score for a job.
    """
    score = 0
    for skill in skills:
        level = skill.get("level")
        score += skill_level_mapping.get(level, 0)
    return score

df["skill_level_score"] = df["skills_normalized"].apply(calculate_skill_level_score)

In [12]:
df["skill_level_score"].describe()

count    12037.000000
mean         4.718867
std          4.873854
min          0.000000
25%          0.000000
50%          4.000000
75%          7.000000
max         54.000000
Name: skill_level_score, dtype: float64

## Advanced Skill Ratio
This feature measures the proportion of advanced-level skills required by a job.
It helps identify highly specialized positions.

In [13]:
def calculate_advanced_ratio(skills):
    """
    Calculate the ratio of advanced skills.
    """
    if len(skills) == 0:
        return 0
    advanced_count = sum(1 for skill in skills if skill.get("level") == "Advanced")
    return advanced_count / len(skills)

df["advanced_skill_ratio"] = df["skills_normalized"].apply(calculate_advanced_ratio)

In [14]:
df["advanced_skill_ratio"].describe()

count    12037.000000
mean         0.182825
std          0.328889
min          0.000000
25%          0.000000
50%          0.000000
75%          0.250000
max          1.000000
Name: advanced_skill_ratio, dtype: float64

In [15]:
def normalize_skill_name(skill):
    """
    Normalize skill names for matching.
    """
    return (skill.lower().strip().replace(" ", "_"))

def extract_skill_set(skills):
    """
    Convert list of skill dictionaries into normalized skill set.
    """
    return {normalize_skill_name(skill["skill"]) for skill in skills if "skill" in skill}

df["required_skills_set"] = df["skills_normalized"].apply(extract_skill_set)

In [16]:
df[["skills_normalized", "required_skills_set"]].sample(5, random_state=42)

,skills_normalized,required_skills_set
9432,[],{}
10171,"[{'skill': 'Microsoft Word', 'level': 'Intermediate'}, {'skill': 'Microsoft Excel', 'level': 'Ad...","{microsoft_excel, microsoft_word}"
487,"[{'skill': 'Wordpress', 'level': 'Intermediate'}, {'skill': 'Python', 'level': 'Basic'}, {'skill...","{linux, wordpress, python}"
10890,"[{'skill': 'Google Analytics', 'level': 'Basic'}, {'skill': 'Google Tag Manager', 'level': 'Basi...","{semrush, screaming_frog, google_tag_manager, sitebulb, google_analytics, google_search_console,..."
8688,[],{}

## Experience Level
Experience years are converted into career levels:
- 0 years: Entry Level
- 1-2 years: Junior
- 3-5 years: Mid Level
- 6+ years: Senior
This feature improves job-candidate matching.

In [17]:
df["experience_years"].value_counts().sort_index()

experience_years
0     1036
1     1572
2     2952
3     3318
4      542
5     1902
6      137
7      185
8       97
9        4
10     271
12       4
15      15
17       1
20       1
Name: count, dtype: int64

In [18]:
def categorize_experience(years):
    """
    Convert numeric experience years into career level.
    """
    if years == 0:
        return "Entry Level"
    elif years <= 2:
        return "Junior"
    elif years <= 5:
        return "Mid Level"
    else:
        return "Senior"
    
df["experience_level"] = df["experience_years"].apply(categorize_experience)
df["experience_level"].value_counts()

experience_level
Mid Level      5762
Junior         4524
Entry Level    1036
Senior          715
Name: count, dtype: int64

In [19]:
df["seniority"].value_counts()

seniority
Specialist                 7170
Senior Specialist          2073
Employee                   1267
Manager                    1172
Worker                      170
Deputy / Senior Manager     138
CEO / Business Head          47
Name: count, dtype: int64

In [20]:
seniority_mapping = {
    "Worker": 1,
    "Employee": 2,
    "Specialist": 3,
    "Senior Specialist": 4,
    "Manager": 5,
    "Deputy / Senior Manager": 6,
    "CEO / Business Head": 7
}

df["seniority_score"] = df["seniority"].map(seniority_mapping)

In [21]:
df[["seniority", "seniority_score"]].sample(10, random_state=42)

                     seniority  seniority_score
9432                Specialist                3
10171               Specialist                3
487                 Specialist                3
10890               Specialist                3
8688                Specialist                3
1483                Specialist                3
11575                 Employee                2
2627   Deputy / Senior Manager                6
3777                Specialist                3
6562                Specialist                3

In [22]:
df["seniority_score"].value_counts().sort_index()

seniority_score
1     170
2    1267
3    7170
4    2073
5    1172
6     138
7      47
Name: count, dtype: int64

## Work Type Features
Work type information is transformed into numerical and binary features.
- Work type score represents flexibility level.
- Flexible work flag identifies non-full-time opportunities.

In [23]:
df["work_type"].value_counts()

work_type
Full Time                 10548
Full Time Or Part Time      685
Part Time                   423
Project - based             381
Name: count, dtype: int64

In [24]:
work_type_mapping = {
    "Full Time": 1,
    "Part Time": 2,
    "Full Time Or Part Time": 3,
    "Project - based": 4
}

df["work_type_score"] = df["work_type"].map(work_type_mapping)

In [25]:
flexible_types = [
    "Part Time",
    "Full Time Or Part Time",
    "Project - based"
]

df["flexible_work"] = df["work_type"].isin(flexible_types)

In [26]:
df[
    [
        "work_type",
        "work_type_score",
        "flexible_work"
    ]
].sample(
    10,
    random_state=42
)

                    work_type  work_type_score  flexible_work
9432                Full Time                1          False
10171               Full Time                1          False
487                 Full Time                1          False
10890  Full Time Or Part Time                3           True
8688                Part Time                2           True
1483   Full Time Or Part Time                3           True
11575               Full Time                1          False
2627                Full Time                1          False
3777                Full Time                1          False
6562                Full Time                1          False

In [27]:
df["flexible_work"].value_counts()

flexible_work
False    10548
True      1489
Name: count, dtype: int64

In [28]:
df["is_remote"] = df["remote"].astype(int)
df["is_remote"].value_counts()

is_remote
0    11331
1      706
Name: count, dtype: int64

In [29]:
df["is_internship"] = df["internship"].astype(int)
df["is_internship"].value_counts()

is_internship
0    11762
1      275
Name: count, dtype: int64

In [30]:
df["military_option"] = df["military"].astype(int)

In [31]:
df["candidate_friendly_score"] = (df["is_remote"] + df["is_internship"] + df["military_option"])

In [32]:
df["candidate_friendly_score"].value_counts().sort_index()

candidate_friendly_score
0    6141
1    5729
2     164
3       3
Name: count, dtype: int64

In [33]:
df["city"].value_counts().head(20)

city
تهران      7195
اصفهان      555
مشهد        514
کرج         327
شیراز       222
قم          197
یزد         124
رشت         119
تبریز       118
پردیس       113
کرمان       110
اهواز       101
ساری         75
قزوین        71
شهر قدس      69
بابل         66
آمل          59
پاکدشت       57
ساوه         55
گرگان        54
Name: count, dtype: int64

In [34]:
city_frequency = df["city"].value_counts()
df["city_job_market_score"] = (df["city"].map(city_frequency).apply(np.log1p))

In [35]:
df[["city", "city_job_market_score"]].drop_duplicates().sort_values("city_job_market_score", ascending=False)[:10]

      city  city_job_market_score
0    تهران               8.881281
26  اصفهان               6.320768
41    مشهد               6.244167
21     کرج               5.793014
31   شیراز               5.407172
39      قم               5.288267
32     یزد               4.828314
67     رشت               4.787492
38   تبریز               4.779123
12   پردیس               4.736198

In [36]:
province_frequency = df["province"].value_counts()
df["province_job_market_score"] = (df["province"].map(province_frequency).apply(np.log1p))
df["is_tehran"] = (df["city"] == "تهران").astype(int)

In [37]:
df[["city", "city_job_market_score", "province_job_market_score", "is_tehran"]].sample(10, random_state=42)

         city  city_job_market_score  province_job_market_score  is_tehran
9432    تهران               8.881281                   8.973605          1
10171   تهران               8.881281                   8.973605          1
487     تهران               8.881281                   8.973605          1
10890  هشتگرد               3.496508                   6.340359          0
8688    سمنان               3.663562                   4.442651          0
1483    تهران               8.881281                   8.973605          1
11575   تهران               8.881281                   8.973605          1
2627    تهران               8.881281                   8.973605          1
3777    تهران               8.881281                   8.973605          1
6562     پرند               3.784190                   8.973605          0

In [38]:
df[["salary_min", "salary_max"]].describe()

        salary_min   salary_max
count  4083.000000  4083.000000
mean     37.957384    52.469753
std      21.876399    30.006634
min       3.000000     4.000000
25%      25.000000    35.000000
50%      30.000000    45.000000
75%      45.000000    60.000000
max     300.000000   400.000000

In [39]:
df[["salary_min", "salary_max"]].dropna()[:10]

    salary_min  salary_max
6         47.0        70.0
7         40.0        50.0
13        60.0        85.0
17        45.0        60.0
18        30.0        40.0
21        30.0        45.0
24        50.0        75.0
31        60.0        75.0
33        30.0        31.0
34       100.0       150.0

In [40]:
df["has_salary_info"] = df["salary_min"].notna().astype(int)

df["salary_avg"] = (df["salary_min"] + df["salary_max"]) / 2

df["salary_range"] = (df["salary_max"] - df["salary_min"])

In [41]:
df[["salary_min", "salary_max", "salary_avg", "salary_range", "has_salary_info"]].dropna().sample(10, random_state=42)

       salary_min  salary_max  salary_avg  salary_range  has_salary_info
2133         35.0        40.0        37.5           5.0                1
2562         25.0        30.0        27.5           5.0                1
8926         20.0        32.0        26.0          12.0                1
9510         25.0        30.0        27.5           5.0                1
8211         20.0        25.0        22.5           5.0                1
7763         30.0        35.0        32.5           5.0                1
2381         60.0        65.0        62.5           5.0                1
1207         24.0        35.0        29.5          11.0                1
519          20.0        30.0        25.0          10.0                1
10373        80.0       120.0       100.0          40.0                1

In [42]:
df["salary_avg"].quantile([0.25, 0.5, 0.75])

0.25    30.0
0.50    37.5
0.75    52.5
Name: salary_avg, dtype: float64

In [43]:
salary_q1 = df["salary_avg"].quantile(0.25)
salary_q3 = df["salary_avg"].quantile(0.75)


def categorize_salary(salary):
    """
    Convert salary value into market level.
    """
    if pd.isna(salary):
        return "Unknown"
    elif salary <= salary_q1:
        return "Low"
    elif salary <= salary_q3:
        return "Medium"
    else:
        return "High"

df["salary_level"] = df["salary_avg"].apply(categorize_salary)
df["salary_level"].value_counts()

salary_level
Unknown    7954
Medium     1905
Low        1231
High        947
Name: count, dtype: int64

In [44]:
df[["salary_avg", "salary_level"]].sample(10, random_state=42)

       salary_avg salary_level
9432          NaN      Unknown
10171         NaN      Unknown
487           NaN      Unknown
10890         NaN      Unknown
8688          NaN      Unknown
1483         55.0         High
11575         NaN      Unknown
2627          NaN      Unknown
3777          NaN      Unknown
6562          NaN      Unknown

In [45]:
OUTPUT_DIR = Path("../data/processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
output_path = OUTPUT_DIR / "jobs_featured_cleaned.csv"
df.to_csv(OUTPUT_DIR / "jobs_featured_cleaned.csv", index=False, encoding="utf-8-sig")
print(f"Dataset saved to: {output_path}")

Dataset saved to: ..\data\processed\jobs_featured_cleaned.csv